### PR TITLE
Fix handling of invalid modification to json file

### LINKED ISSUE #432: [PE-D][Tester A] Application crash as a result of null value in Json
Image

The case where the user edits the TAHUB.json with null as a record could be handled better. If you make this change to the TAHUB.json

Image

you will encounter a null pointer exception such as below

Image

This is inconsistent with the documentation in the User Guide, that states that if the user's changes makes the data file format invalid, the application will start with an empty data file, since in this case, the application just crashes. I recommend parsing the format of all entries in the Json extensively before allowing the application to start running.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #449: [PE-D][Tester A] Application crashes with ArrayIndexOutOfBoundsException when editing TAHUB.json with more than 13 weeks of entries
Image

In the case the user edits the TAHUB.json to edit a particular student's scores for a certain week, but instead accidentally duplicates that entry, it will result in the application crashing with a ArrayIndexOutOfBoundsException the next time it starts. 

Image

This behaviour can be reproduced by copying one of the entries and pasting at the end of the recordList array.

Image

This does not follow the specification of the User Guide which states that a json file with invalid formatting will be written over with an empty data file.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by jarretphon**
Fixes #449 
Fixes #432

### CODE REVIEW

File: src/main/java/seedu/address/storage/JsonAdaptedStudent.java [hunk 1]
```diff
@@ -85,13 +87,21 @@ public JsonAdaptedStudent(Student source) {
...
         final List<Tag> studentTags = new ArrayList<>();
         for (JsonAdaptedTag tag : tags) {
-            studentTags.add(tag.toModelType());
+            if (tag != null) {
+                studentTags.add(tag.toModelType());
+            }
+        }
+
+        if (recordList.size() > WeekNumber.MAX_WEEK_NUMBER) {
+            throw new IllegalValueException(String.format(INVALID_RECORD_LIST_LENGTH_MESSAGE_FORMAT));
```
Comment (kailermai) [inline src/main/java/seedu/address/storage/JsonAdaptedStudent.java]: String.format method seems redundant, would it still work with just `throw new IllegalValueException(INVALID_RECORD_LIST_LENGTH_MESSAGE_FORMAT);`?

Comment (jarretphon) [reply src/main/java/seedu/address/storage/JsonAdaptedStudent.java]: removed!

**Review by liawjarell — COMMENTED** [review]
LGTM.
