### PR TITLE
Fix bugs find in alpha test about sort feature

### LINKED ISSUE #294: Sort feature: Incorrect sorting
Irfan Ibrahim currently has the following records. 
Image

After sort was ran, Irfan was placed below David Li, and above Roy. Even though Irfan already had one record entry, with all 0s for all three fields. David and Roy did not have any records entered yet. This could be a feature flaw. Given that David and Roy did not have an entry yet, we could display at the bottom of the list, below all students who already had a record entry.
Image

### LINKED ISSUE #295: Sort Feature: Parsing error
Input as specified below still sorts the list according to submission. Is this perhaps an intentional feature?
Image

This is unlike other commands, as shown below:

Image

Image

### LINKED ISSUE #297: Sort Command: UG
Perhaps this could be split across multiple lines for better readability?
Image

### LINKED ISSUE #308: Sort feature: Sort command's help description format in help panel does not follow the convention for other commands
Other commands in the help panel follows the format of [prefix]/[parameter name]. Consider displaying the command format as sort /FILTER_KEYWORD or placing each command format on a separate lines.
Image

### LINKED ISSUE #309: Sort feature: Invalid command display format
Consider placing the examples of sort commands on different lines or separated by commas to improve readability and reduce confusion
Image

### LINKED ISSUE #311: Formatting for help message for multiple features
Find and delete commands are missing a colon after the header
EG: Find student: instead of Find student

Sort command also has a fullstop instead of a colon at the end of the header

Image

### PR DESCRIPTION
**Pull request by lqr1019**
Fixes #311 
Fixes #309 
Fixes #308 
Fixes #297 
Fixes #295
Fixes #294

### CODE REVIEW

File: src/test/java/seedu/address/logic/parser/SortCommandParserTest.java [hunk 1]
```diff
@@ -13,9 +13,9 @@ public class SortCommandParserTest {
 
     @Test
     public void parse_validArgs_returnsSortCommand() {
-        assertParseSuccess(parser, "sort /a", new SortCommand(true, false, false));
-        assertParseSuccess(parser, "sort /p", new SortCommand(false, true, false));
-        assertParseSuccess(parser, "sort /s", new SortCommand(false, false, true));
+        assertParseSuccess(parser, " /a", new SortCommand(true, false, false));
+        assertParseSuccess(parser, " /p", new SortCommand(false, true, false));
+        assertParseSuccess(parser, " /s", new SortCommand(false, false, true));
```
Comment (liawjarell) [inline src/test/java/seedu/address/logic/parser/SortCommandParserTest.java]: Perhaps you could replace `" /a"` with `PREAMBLE_WHITESPACE + `PREFIX_SORT_ATTENDANCE`, similar to other CommandParse test functions?
